create database warzone;
use warzone;

create table tech (
    id int not null auto_increment,
    name varchar(255) not null,
    primary key (id)
);

create table dependency (
    tech int not null,
    req int not null,
    foreign key (tech) references tech(id),
    foreign key (req) references tech(id)
);

create table temp (
	tech varchar(255),
	name1 varchar(255),
    name2 varchar(255),
    name3 varchar(255),
    name4 varchar(255),
    name5 varchar(255),
    name6 varchar(255)
);

insert into tech (name) values
('AA Ammunition Hopper'),
('AA Ammunition Hopper Mk2'),
('AA Ammunition Hopper Mk3'),
('AA Chainfeed Loader'),
('AA Chainfeed Loader Mk2'),
('AA Chainfeed Loader Mk3'),
('AA HE Flak'),
('AA HE Flak Mk2'),
('AA HE Flak Mk3'),
('AA HEAP Flak'),
('AA HEAP Flak Mk2'),
('AA HEAP Flak Mk3'),
('AA Target Acquisition Shells'),
('AA Target Prediction Computer'),
('AA Thermal Imaging Sensor'),
('Advanced Base Structure Materials'),
('Advanced Base Structure Materials Mk2'),
('Advanced Base Structure Materials Mk3'),
('Advanced Cyborg Production'),
('Advanced Cyborg Production Mk2'),
('Advanced Cyborg Production Mk3'),
('Advanced Engineering'),
('Advanced Factory Production'),
('Advanced Factory Production Mk2'),
('Advanced Factory Production Mk3'),
('Advanced Missile Allocation System'),
('Advanced Missile Allocation System Mk2'),
('Advanced Missile Allocation System Mk3'),
('Advanced Missile Warhead'),
('Advanced Missile Warhead Mk2'),
('Advanced Missile Warhead Mk3'),
('Advanced VTOL Production'),
('Advanced VTOL Production Mk2'),
('Advanced VTOL Production Mk3'),
('Angel Missile'),
('Angel Missile Battery'),
('APDSB MG Bullets'),
('APDSB MG Bullets Mk2'),
('APFSDS Cannon Rounds'),
('APFSDS Cannon Rounds Mk2'),
('APFSDS Cannon Rounds Mk3'),
('Archangel Missile'),
('Archangel Missile Battery'),
('Assault Cannon'),
('Assault Cannon Hardpoint'),
('Assault Gun'),
('Assault Gun Emplacement'),
('Assault Gun Hardpoint'),
('Automated Cyborg Production'),
('Automated Cyborg Production Mk2'),
('Automated Cyborg Production Mk3'),
('Automated Factory Production'),
('Automated Factory Production Mk2'),
('Automated Factory Production Mk3'),
('Automated Repair Facility'),
('Automated Repair Facility Upgrade Mk2'),
('Automated Repair Facility Upgrade Mk3'),
('Automated VTOL Rearming'),
('Automated VTOL Rearming Mk2'),
('Automated VTOL Rearming Mk3'),
('Auto-Repair'),
('Avenger Hardpoint'),
('Avenger SAM'),
('Avenger SAM Site'),
('Bombard Pit'),
('Bunker Buster Rocket'),
('Cannon Autoloader'),
('Cannon Autoloader Mk2'),
('Cannon Autoloader Mk3'),
('Cannon Fortress'),
('Cannon Laser Designator'),
('Cannon Laser Rangefinder'),
('Cannon Rapid Loader'),
('Cannon Rapid Loader Mk2'),
('Cannon Rapid Loader Mk3'),
('CB Tower'),
('CB Turret'),
('Chaingun Upgrade'),
('Cluster Bombs Bay'),
('Combat Engineer'),
('Command Relay Post'),
('Command Turret'),
('Command Turret Mk2'),
('Command Turret Mk3'),
('Command Turret Mk4'),
('Composite Alloys'),
('Composite Alloys Mk2'),
('Composite Alloys Mk3'),
('Cyborg Composite Alloys'),
('Cyborg Composite Alloys Mk2'),
('Cyborg Composite Alloys Mk3'),
('Cyborg Dense Composite Alloys'),
('Cyborg Dense Composite Alloys Mk2'),
('Cyborg Dense Composite Alloys Mk3'),
('Cyborg Factory'),
('Cyborg High Intensity Thermal Armor'),
('Cyborg High Intensity Thermal Armor Mk2'),
('Cyborg High Intensity Thermal Armor Mk3'),
('Cyborg Mechanic'),
('Cyborg Superdense Composite Alloys'),
('Cyborg Superdense Composite Alloys Mk2'),
('Cyborg Superdense Composite Alloys Mk3'),
('Cyborg Superdense Thermal Armor'),
('Cyborg Superdense Thermal Armor Mk2'),
('Cyborg Superdense Thermal Armor Mk3'),
('Cyborg Thermal Amour'),
('Cyborg Thermal Amour Mk2'),
('Cyborg Thermal Amour Mk3'),
('Cyborg Transport'),
('Cyclone AA Site'),
('Cyclone Flak Turret'),
('Cyclone Hardpoint'),
('Dedicated Synaptic Link Data Analysis'),
('Dedicated Synaptic Link Data Analysis Mk2'),
('Dedicated Synaptic Link Data Analysis Mk3'),
('Dense Composite Alloys'),
('Dense Composite Alloys Mk2'),
('Dense Composite Alloys Mk3'),
('EMP Cannon'),
('EMP Cannon Tower'),
('EMP Missile Launcher'),
('EMP Mortar'),
('Engineering'),
('Factory Module'),
('Fast Fire Mini-Rockets'),
('Fast Fire Mini-Rockets Mk2'),
('Fast Fire Mini-Rockets Mk3'),
('Fast Loader'),
('Flamer'),
('Flamer Autoloader'),
('Flamer Autoloader Mk2'),
('Flamer Autoloader Mk3'),
('Flamer Bunker'),
('Flashlight Emplacement'),
('Flashlight Gunner'),
('Flashlight Hardpoint'),
('Fuel Injection Engine'),
('Fuel Injection Engine Mk2'),
('Fuel Injection Engine Mk3'),
('Gas Turbine Engine'),
('Gas Turbine Engine Mk2'),
('Gas Turbine Engine Mk3'),
('Gas Turbine Generator'),
('Gauss Cannon'),
('Gauss Cannon Emplacement'),
('Gauss Cannon Hardpoint'),
('Grenadier'),
('Ground Shaker Emplacement'),
('Half-tracked Propulsion'),
('Hardcrete'),
('Hardened Base Structure Materials'),
('Hardened Base Structure Materials Mk2'),
('Hardened Base Structure Materials Mk3'),
('Hardened MG Bullets'),
('Hardened Rail Dart'),
('Hardened Rail Dart Mk2'),
('Hardened Rail Dart Mk3'),
('Hardened Sensor Tower'),
('HE Howitzer Shells'),
('HE Howitzer Shells Mk2'),
('HE Howitzer Shells Mk3'),
('HE Mini-Rockets'),
('HE Mini-Rockets Mk2'),
('HE Mini-Rockets Mk3'),
('HE Mortar Shells'),
('HE Mortar Shells Mk2'),
('HE Mortar Shells Mk3'),
('HEAP Bomb Bay'),
('HEAP Howitzer Shells'),
('HEAP Howitzer Shells Mk2'),
('HEAP Howitzer Shells Mk3'),
('HEAP Mini-Rockets'),
('HEAP Mini-Rockets Mk2'),
('HEAP Mini-Rockets Mk3'),
('HEAP Mortar Shells'),
('HEAP Mortar Shells Mk2'),
('HEAP Mortar Shells Mk3'),
('HEAT Cannon Shells'),
('HEAT Cannon Shells Mk2'),
('HEAT Cannon Shells Mk3'),
('HEAT Rocket Warhead'),
('HEAT Rocket Warhead Mk2'),
('HEAT Rocket Warhead Mk3'),
('Heavy Body - Mantis'),
('Heavy Body - Python'),
('Heavy Body - Tiger'),
('Heavy Body - Vengeance'),
('Heavy Cannon'),
('Heavy Cannon Hardpoint'),
('Heavy Flamer - Inferno'),
('Heavy Gunner'),
('Heavy Howitzer - Ground Shaker'),
('Heavy Laser'),
('Heavy Laser Emplacement'),
('Heavy Machinegun'),
('Heavy Machinegun Hardpoint'),
('Heavy Mortar - Bombard'),
('Heavy Repair Turret'),
('Heavy Rocket Bastion'),
('Hellstorm Emplacement'),
('HESH Rocket Warhead'),
('HESH Rocket Warhead Mk2'),
('HESH Rocket Warhead Mk3'),
('Hi-Energy Laser Emitter'),
('Hi-Energy Laser Emitter Mk2'),
('Hi-Energy Laser Emitter Mk3'),
('High Intensity Thermal Armor'),
('High Intensity Thermal Armor Mk2'),
('High Intensity Thermal Armor Mk3'),
('High Temperature Flamer Gel'),
('High Temperature Flamer Gel Mk2'),
('High Temperature Flamer Gel Mk3'),
('Hover Propulsion'),
('Howitzer'),
('Howitzer Autoloader'),
('Howitzer Autoloader Mk2'),
('Howitzer Autoloader Mk3'),
('Howitzer Emplacement'),
('HPV Cannon Emplacement'),
('HPV Cannon Hardpoint'),
('Hurricane AA Site'),
('Hurricane AA Turret'),
('HVAPFSDS Cannon Rounds'),
('HVAPFSDS Cannon Rounds Mk2'),
('HVAPFSDS Cannon Rounds Mk3'),
('Hyper Fire Chaingun Upgrade'),
('Hyper Velocity Cannon'),
('Improved Engineering'),
('Improved Hardcrete'),
('Improved Hardcrete Mk2'),
('Improved Hardcrete Mk3'),
('Improved Laser Focusing'),
('Improved Rocket Wire Guidance'),
('Incendiary Howitzer'),
('Incendiary Howitzer Emplacement'),
('Incendiary Mortar'),
('Inferno Emplacement'),
('Lancer'),
('Lancer AT Rocket'),
('Lancer Bunker'),
('Lancer Hardpoint'),
('Laser - Flashlight'),
('Laser Guided Bombsight'),
('Laser Satellite Command Post'),
('Light Body - Bug'),
('Light Body - Leopard'),
('Light Body - Retaliation'),
('Light Cannon'),
('Light Cannon Bunker'),
('Light Cannon Hardpoint'),
('Machine Gunner'),
('Machinegun'),
('Machinegun Bunker'),
('Machinegun Guard Tower'),
('Mass Driver Fortress'),
('Medium Body - Cobra'),
('Medium Body - Panther'),
('Medium Body - Retribution'),
('Medium Body - Scorpion'),
('Medium Cannon'),
('Medium Cannon Hardpoint'),
('Mini-Pod Rocket Guard Tower'),
('Mini-Pod Rockets'),
('Mini-Rocket Artillery'),
('Mini-Rocket Battery'),
('Missile Fortress'),
('Mobile Repair Turret'),
('Mortar'),
('Mortar Autoloader'),
('Mortar Autoloader Mk2'),
('Mortar Autoloader Mk3'),
('Mortar Fast Loader'),
('Mortar Pit'),
('Mortar Targeting Computer'),
('Needle Gun'),
('Needle Gun Tower'),
('Needle Gunner'),
('Neural Synapse Research Brain'),
('Neural Synapse Research Brain Mk2'),
('Neural Synapse Research Brain Mk3'),
('Nexus Link Tower'),
('Nexus Link Turret'),
('Pepperpot Pit'),
('Phosphor Bomb Bay'),
('Plascrete'),
('Plascrete Mk2'),
('Plascrete MK3'),
('Plasma Cannon'),
('Plasma Cannon Emplacement'),
('Plasmite Bomb'),
('Plasmite Flamer'),
('Plasteel'),
('Plasteel Mk2'),
('Plasteel Mk3'),
('Power Module'),
('Pulse Laser'),
('Pulse Laser Emplacement'),
('Rail Gun'),
('Rail Gun Emplacement'),
('Rail Gun Hardpoint'),
('Rail Gun ROF'),
('Rail Gun ROF Mk2'),
('Rail Gun ROF Mk3'),
('Rapid Fire Chaingun'),
('Reinforced Base Structure Materials'),
('Reinforced Base Structure Materials Mk2'),
('Reinforced Base Structure Materials Mk3'),
('Repair Facility'),
('Research Module'),
('Resistance Circuits'),
('Ripple Rocket Battery'),
('Ripple Rockets'),
('Robotic Cyborg Production'),
('Robotic Cyborg Production Mk2'),
('Robotic Cyborg Production Mk3'),
('Robotic Factory Production'),
('Robotic Factory Production Mk2'),
('Robotic Factory Production Mk3'),
('Robotic Repair Facility Upgrade'),
('Robotic Repair Facility Upgrade Mk2'),
('Robotic Repair Facility Upgrade Mk3'),
('Robotic VTOL Production'),
('Robotic VTOL Production Mk2'),
('Robotic VTOL Production Mk3'),
('Robotic VTOL Rearming'),
('Robotic VTOL Rearming Mk2'),
('Robotic VTOL Rearming Mk3'),
('Rocket Autoloader'),
('Rocket Autoloader Mk2'),
('Rocket Laser Designator'),
('Rotary Howitzer - Hellstorm'),
('Rotary Mortar - Pepperpot'),
('Satellite Uplink Center'),
('Scourge'),
('Scourge Missile'),
('Scourge Missile Hardpoint'),
('Scourge Missile Tower'),
('Search & Destroy Missiles'),
('Sensor Tower'),
('Sensor Turret'),
('Sensor Upgrade'),
('Stabilized Mini-Rockets'),
('Stabilized Mini-Rockets Mk2'),
('Stormbringer AA Laser'),
('Super Auto-Cannon Cyborg'),
('Super Heavy Body - Dragon'),
('Super Heavy Body - Wyvern'),
('Super Heavy-Gunner'),
('Super HPV Cyborg'),
('Super Pulse Laser Cyborg'),
('Super Rail-Gunner'),
('Super Scourge Cyborg'),
('Super Tank-Killer Cyborg'),
('Supercrete'),
('Supercrete Mk2'),
('Supercrete Mk3'),
('Superdense Composite Alloys'),
('Superdense Composite Alloys Mk2'),
('Superdense Composite Alloys Mk3'),
('Superhot Flamer Gel'),
('Superhot Flamer Gel Mk2'),
('Superhot Flamer Gel Mk3'),
('Superhot Plasmite gel'),
('Superhot Plasmite gel Mk2'),
('Superhot Plasmite gel Mk3'),
('Synaptic Link Data Analysis'),
('Synaptic Link Data Analysis Mk2'),
('Synaptic Link Data Analysis Mk3'),
('Tank Killer Emplacement'),
('Tank Killer Hardpoint'),
('Tank Killer Rocket'),
('Tank Traps'),
('Target Acquisition Artillery Shells'),
('Target Acquisition Artillery Shells Mk2'),
('Target Acquisition Bombsight'),
('Target Acquisition Mortar Shells'),
('Target Prediction Artillery Shells'),
('Target Prediction Computer'),
('Target Prediction Missiles'),
('Thermal Amour'),
('Thermal Amour Mk2'),
('Thermal Amour Mk3'),
('Thermal Imaging Bombsight'),
('Thermal Imaging Mortar Shells'),
('Thermal Imaging Rockets'),
('Thermite Bomb Bay'),
('Thermite Flamer'),
('Thermopole Energizer'),
('Thermopole Energizer Mk2'),
('Thermopole Energizer Mk3'),
('Tracked Propulsion'),
('Turbo-Charged Engine'),
('Turbo-Charged Engine Mk2'),
('Turbo-Charged Engine Mk3'),
('Twin Assault Cannon'),
('Twin Assault Cannon Bunker'),
('Twin Assault Gun'),
('Twin Machinegun'),
('Vapor Turbine Generator'),
('Vehicle Superdense Thermal Armor'),
('Vehicle Superdense Thermal Armor Mk2'),
('Vehicle Superdense Thermal Armor Mk3'),
('Vindicator Hardpoint'),
('Vindicator SAM'),
('Vindicator SAM Site'),
('VTOL CB Tower'),
('VTOL CB Turret'),
('VTOL Factory'),
('VTOL Propulsion'),
('VTOL Rearming Pad'),
('VTOL Strike Tower'),
('VTOL Strike Turret'),
('Whirlwind AA Site'),
('Whirlwind AA Turret'),
('Whirlwind Hardpoint'),
('Wide Spectrum Sensor'),
('Wide Spectrum Sensor Tower');

insert into temp values
('AA Ammunition Hopper', 'AA HE Flak', 'Chaingun Upgrade', null, null, null, null),
('AA Ammunition Hopper Mk2', 'AA Ammunition Hopper', null, null, null, null, null),
('AA Ammunition Hopper Mk3', 'Whirlwind AA Turret', 'AA Ammunition Hopper Mk2', null, null, null, null),
('AA Chainfeed Loader', 'Cannon Rapid Loader', null, null, null, null, null),
('AA Chainfeed Loader Mk2', 'AA Chainfeed Loader', null, null, null, null, null),
('AA Chainfeed Loader Mk3', 'AA Chainfeed Loader Mk2', null, null, null, null, null),
('AA HE Flak', 'Hurricane AA Turret', null, null, null, null, null),
('AA HE Flak Mk2', 'AA HE Flak', null, null, null, null, null),
('AA HE Flak Mk3', 'AA HE Flak Mk2', null, null, null, null, null),
('AA HEAP Flak', 'HVAPFSDS Cannon Rounds Mk2', null, null, null, null, null),
('AA HEAP Flak Mk2', 'AA HEAP Flak', null, null, null, null, null),
('AA HEAP Flak Mk3', 'AA HEAP Flak Mk2', null, null, null, null, null),
('AA Target Acquisition Shells', 'Target Acquisition Artillery Shells', 'AA Thermal Imaging Sensor', null, null, null, null),
('AA Target Prediction Computer', 'Target Prediction Computer', 'AA Target Acquisition Shells', null, null, null, null),
('AA Thermal Imaging Sensor', 'Thermal Imaging Rockets', null, null, null, null, null),
('Advanced Base Structure Materials', 'Plascrete', 'Hardened Base Structure Materials Mk3', null, null, null, null),
('Advanced Base Structure Materials Mk2', 'Advanced Base Structure Materials', null, null, null, null, null),
('Advanced Base Structure Materials Mk3', 'Advanced Base Structure Materials Mk2', null, null, null, null, null),
('Advanced Cyborg Production', 'Advanced Engineering', null, null, null, null, null),
('Advanced Cyborg Production Mk2', 'Advanced Cyborg Production', null, null, null, null, null),
('Advanced Cyborg Production Mk3', 'Advanced Cyborg Production Mk2', null, null, null, null, null),
('Advanced Engineering', 'Neural Synapse Research Brain Mk2', 'Improved Engineering', null, null, null, null),
('Advanced Factory Production', 'Advanced Engineering', null, null, null, null, null),
('Advanced Factory Production Mk2', 'Advanced Factory Production', null, null, null, null, null),
('Advanced Factory Production Mk3', 'Advanced Factory Production Mk2', null, null, null, null, null),
('Advanced Missile Allocation System', 'Scourge Missile', null, null, null, null, null),
('Advanced Missile Allocation System Mk2', 'Advanced Missile Allocation System', null, null, null, null, null),
('Advanced Missile Allocation System Mk3', 'Advanced Missile Allocation System Mk2', null, null, null, null, null),
('Advanced Missile Warhead', 'Avenger SAM', null, null, null, null, null),
('Advanced Missile Warhead Mk2', 'Advanced Missile Warhead', null, null, null, null, null),
('Advanced Missile Warhead Mk3', 'Advanced Missile Warhead Mk2', null, null, null, null, null),
('Advanced VTOL Production', 'Robotic VTOL Production Mk3', null, null, null, null, null),
('Advanced VTOL Production Mk2', 'Advanced VTOL Production', null, null, null, null, null),
('Advanced VTOL Production Mk3', 'Advanced VTOL Production Mk2', null, null, null, null, null),
('Angel Missile', 'Advanced Missile Warhead Mk2', 'Ripple Rockets', 'Scourge Missile', null, null, null),
('Angel Missile Battery', 'Angel Missile', null, null, null, null, null),
('APDSB MG Bullets', 'Hardened MG Bullets', null, null, null, null, null),
('APDSB MG Bullets Mk2', 'APDSB MG Bullets', null, null, null, null, null),
('APFSDS Cannon Rounds', 'HEAT Cannon Shells Mk3', null, null, null, null, null),
('APFSDS Cannon Rounds Mk2', 'APFSDS Cannon Rounds', null, null, null, null, null),
('APFSDS Cannon Rounds Mk3', 'APFSDS Cannon Rounds Mk2', null, null, null, null, null),
('Archangel Missile', 'Angel Missile', 'Advanced Missile Warhead Mk3', null, null, null, null),
('Archangel Missile Battery', 'Archangel Missile', null, null, null, null, null),
('Assault Cannon', 'Medium Cannon', 'Cannon Autoloader Mk3', null, null, null, null),
('Assault Cannon Hardpoint', 'Assault Cannon', null, null, null, null, null),
('Assault Gun', 'Heavy Machinegun', 'Hyper Fire Chaingun Upgrade', null, 'Machinegun', 'Twin Machinegun', 'Heavy Machinegun'),
('Assault Gun Emplacement', 'Assault Gun', null, null, null, null, null),
('Assault Gun Hardpoint', 'Assault Gun', 'Assault Gun Emplacement', null, null, null, null),
('Automated Cyborg Production', 'Factory Module', 'Cyborg Factory', null, null, null, null),
('Automated Cyborg Production Mk2', 'Automated Cyborg Production', null, null, null, null, null),
('Automated Cyborg Production Mk3', 'Automated Cyborg Production Mk2', null, null, null, null, null),
('Automated Factory Production', 'Factory Module', null, null, null, null, null),
('Automated Factory Production Mk2', 'Automated Factory Production', null, null, null, null, null),
('Automated Factory Production Mk3', 'Automated Factory Production Mk2', null, null, null, null, null),
('Automated Repair Facility', 'Automated Factory Production', 'Repair Facility', null, null, null, null),
('Automated Repair Facility Upgrade Mk2', 'Automated Repair Facility', 'Automated Factory Production Mk2', null, null, null, null),
('Automated Repair Facility Upgrade Mk3', 'Automated Factory Production Mk3', 'Automated Repair Facility Upgrade Mk2', null, null, null, null),
('Automated VTOL Rearming', 'VTOL Rearming Pad', null, null, null, null, null),
('Automated VTOL Rearming Mk2', 'Automated VTOL Rearming', null, null, null, null, null),
('Automated VTOL Rearming Mk3', 'Automated VTOL Rearming Mk2', null, null, null, null, null),
('Auto-Repair', 'Neural Synapse Research Brain Mk2', null, null, null, null, null),
('Avenger Hardpoint', 'Plascrete', 'Avenger SAM Site', null, null, null, null),
('Avenger SAM', 'VTOL Strike Tower', 'Scourge Missile', null, null, null, null),
('Avenger SAM Site', 'Avenger SAM', null, null, null, null, null),
('Bombard Pit', 'Mortar Pit', 'Heavy Mortar - Bombard', null, null, null, null),
('Bunker Buster Rocket', 'Lancer AT Rocket', 'HEAT Rocket Warhead Mk3', null, null, null, null),
('Cannon Autoloader', 'APFSDS Cannon Rounds', null, null, null, null, null),
('Cannon Autoloader Mk2', 'Robotic Factory Production', 'Cannon Autoloader', null, null, null, null),
('Cannon Autoloader Mk3', 'Cannon Autoloader Mk2', null, null, null, null, null),
('Cannon Fortress', 'APFSDS Cannon Rounds Mk2', 'Supercrete Mk2', null, null, null, null),
('Cannon Laser Designator', 'Dedicated Synaptic Link Data Analysis', 'Cannon Laser Rangefinder', null, null, null, null),
('Cannon Laser Rangefinder', 'HEAT Cannon Shells Mk2', 'Synaptic Link Data Analysis', null, null, null, null),
('Cannon Rapid Loader', 'HVAPFSDS Cannon Rounds', 'Cannon Autoloader Mk3', null, null, null, null),
('Cannon Rapid Loader Mk2', 'Cannon Rapid Loader', null, null, null, null, null),
('Cannon Rapid Loader Mk3', 'Cannon Rapid Loader Mk2', null, null, null, null, null),
('CB Tower', 'Sensor Upgrade', 'HE Mortar Shells Mk3', null, null, null, null),
('CB Turret', 'CB Tower', null, null, null, null, null),
('Chaingun Upgrade', 'Automated Factory Production', 'APDSB MG Bullets Mk2', null, null, null, null),
('Cluster Bombs Bay', 'VTOL Propulsion', null, null, null, null, null),
('Combat Engineer', 'Engineering', 'Machine Gunner', null, null, null, null),
('Command Relay Post', 'Sensor Tower', null, null, null, null, null),
('Command Turret', 'Command Relay Post', null, null, null, null, null),
('Command Turret Mk2', 'Composite Alloys Mk3', 'Command Turret', 'Command Turret', null, null, null),
('Command Turret Mk3', 'Command Turret Mk2', 'Dense Composite Alloys Mk3', 'Command Turret Mk2', null, null, null),
('Command Turret Mk4', 'Command Turret Mk3', 'Superdense Composite Alloys Mk3', 'Command Turret Mk3', null, null, null),
('Composite Alloys', 'Factory Module', 'Research Module', null, null, null, null),
('Composite Alloys Mk2', 'Composite Alloys', null, null, null, null, null),
('Composite Alloys Mk3', 'Composite Alloys Mk2', null, null, null, null, null),
('Cyborg Composite Alloys', 'Factory Module', 'Research Module', 'Machine Gunner', null, null, null),
('Cyborg Composite Alloys Mk2', 'Cyborg Composite Alloys', null, null, null, null, null),
('Cyborg Composite Alloys Mk3', 'Cyborg Composite Alloys Mk2', 'Machine Gunner', null, null, null, null),
('Cyborg Dense Composite Alloys', 'Cyborg Composite Alloys Mk3', 'Dedicated Synaptic Link Data Analysis', null, null, null, null),
('Cyborg Dense Composite Alloys Mk2', 'Cyborg Dense Composite Alloys', null, null, null, null, null),
('Cyborg Dense Composite Alloys Mk3', 'Cyborg Dense Composite Alloys Mk2', null, null, null, null, null),
('Cyborg Factory', 'Hardened MG Bullets', null, null, null, null, null),
('Cyborg High Intensity Thermal Armor', 'Cyborg Thermal Amour Mk3', 'Cyborg Superdense Composite Alloys', null, null, null, null),
('Cyborg High Intensity Thermal Armor Mk2', 'Cyborg High Intensity Thermal Armor', null, null, null, null, null),
('Cyborg High Intensity Thermal Armor Mk3', 'Cyborg High Intensity Thermal Armor Mk2', null, null, null, null, null),
('Cyborg Mechanic', 'Mobile Repair Turret', 'Machine Gunner', null, null, null, null),
('Cyborg Superdense Composite Alloys', 'Cyborg Dense Composite Alloys Mk3', null, null, null, null, null),
('Cyborg Superdense Composite Alloys Mk2', 'Cyborg Superdense Composite Alloys', null, null, null, null, null),
('Cyborg Superdense Composite Alloys Mk3', 'Cyborg Superdense Composite Alloys Mk2', null, null, null, null, null),
('Cyborg Superdense Thermal Armor', 'Cyborg High Intensity Thermal Armor Mk3', null, null, null, null, null),
('Cyborg Superdense Thermal Armor Mk2', 'Cyborg Superdense Thermal Armor', null, null, null, null, null),
('Cyborg Superdense Thermal Armor Mk3', 'Cyborg Superdense Thermal Armor Mk2', null, null, null, null, null),
('Cyborg Thermal Amour', 'Cyborg Dense Composite Alloys', null, null, null, null, null),
('Cyborg Thermal Amour Mk2', 'Cyborg Thermal Amour', null, null, null, null, null),
('Cyborg Thermal Amour Mk3', 'Cyborg Thermal Amour Mk2', null, null, null, null, null),
('Cyborg Transport', 'Cyborg Factory', 'VTOL Factory', null, null, null, null),
('Cyclone AA Site', 'Cyclone Flak Turret', null, null, null, null, null),
('Cyclone Flak Turret', 'Hurricane AA Turret', 'AA HE Flak Mk2', null, null, null, null),
('Cyclone Hardpoint', 'Cyclone Flak Turret', null, null, null, null, null),
('Dedicated Synaptic Link Data Analysis', 'Synaptic Link Data Analysis Mk3', null, null, null, null, null),
('Dedicated Synaptic Link Data Analysis Mk2', 'Dedicated Synaptic Link Data Analysis', null, null, null, null, null),
('Dedicated Synaptic Link Data Analysis Mk3', 'Dedicated Synaptic Link Data Analysis Mk2', null, null, null, null, null),
('Dense Composite Alloys', 'Dedicated Synaptic Link Data Analysis', 'Composite Alloys Mk3', null, null, null, null),
('Dense Composite Alloys Mk2', 'Dense Composite Alloys', null, null, null, null, null),
('Dense Composite Alloys Mk3', 'Dense Composite Alloys Mk2', null, null, null, null, null),
('EMP Cannon', 'Nexus Link Tower', 'Satellite Uplink Center', null, null, null, null),
('EMP Cannon Tower', 'EMP Cannon', null, null, null, null, null),
('EMP Missile Launcher', 'EMP Cannon', 'Thermite Bomb Bay', null, null, null, null),
('EMP Mortar', 'EMP Cannon Tower', null, null, null, null, null),
('Engineering', null, null, null, null, null, null),
('Factory Module', 'Cyborg Factory', 'Engineering', 'Power Module', null, null, null),
('Fast Fire Mini-Rockets', 'HE Mini-Rockets Mk2', 'Automated Factory Production Mk2', null, null, null, null),
('Fast Fire Mini-Rockets Mk2', 'Fast Fire Mini-Rockets', 'HE Mini-Rockets Mk3', null, null, null, null),
('Fast Fire Mini-Rockets Mk3', 'Fast Fire Mini-Rockets Mk2', null, null, null, null, null),
('Fast Loader', 'Howitzer Autoloader Mk3', null, null, null, null, null),
('Flamer', 'Machinegun', 'Fuel Injection Engine', null, null, null, null),
('Flamer Autoloader', 'High Temperature Flamer Gel Mk2', null, null, null, null, null),
('Flamer Autoloader Mk2', 'Heavy Flamer - Inferno', null, null, null, null, null),
('Flamer Autoloader Mk3', 'Flamer Autoloader Mk2', null, null, null, null, null),
('Flamer Bunker', 'Hardcrete', 'Flamer', null, null, null, null),
('Flashlight Emplacement', 'Laser - Flashlight', null, null, null, null, null),
('Flashlight Gunner', 'Laser - Flashlight', null, null, null, null, null),
('Flashlight Hardpoint', 'Laser - Flashlight', null, null, null, null, null),
('Fuel Injection Engine', 'Engineering', null, null, null, null, null),
('Fuel Injection Engine Mk2', 'Fuel Injection Engine', null, null, null, null, null),
('Fuel Injection Engine Mk3', 'Fuel Injection Engine Mk2', null, null, null, null, null),
('Gas Turbine Engine', 'Light Body - Retaliation', null, null, null, null, null),
('Gas Turbine Engine Mk2', 'Medium Body - Retribution', 'Gas Turbine Engine', null, null, null, null),
('Gas Turbine Engine Mk3', 'Gas Turbine Engine Mk2', 'Heavy Body - Vengeance', null, null, null, null),
('Gas Turbine Generator', 'Dedicated Synaptic Link Data Analysis', 'Power Module', null, null, null, null),
('Gauss Cannon', 'Hardened Rail Dart Mk3', 'Rail Gun', null, null, null, null),
('Gauss Cannon Emplacement', 'Gauss Cannon', null, null, null, null, null),
('Gauss Cannon Hardpoint', 'Gauss Cannon', null, null, null, null, null),
('Grenadier', 'Mortar', 'Machine Gunner', null, null, null, null),
('Ground Shaker Emplacement', 'Howitzer Emplacement', 'Heavy Howitzer - Ground Shaker', null, null, null, null),
('Half-tracked Propulsion', 'Engineering', null, null, null, null, null),
('Hardcrete', 'Engineering', null, null, null, null, null),
('Hardened Base Structure Materials', 'Supercrete', 'Reinforced Base Structure Materials Mk3', null, null, null, null),
('Hardened Base Structure Materials Mk2', 'Hardened Base Structure Materials', null, null, null, null, null),
('Hardened Base Structure Materials Mk3', 'Hardened Base Structure Materials Mk2', null, null, null, null, null),
('Hardened MG Bullets', 'Machinegun', null, null, null, null, null),
('Hardened Rail Dart', 'Needle Gun', null, null, null, null, null),
('Hardened Rail Dart Mk2', 'Hardened Rail Dart', null, null, null, null, null),
('Hardened Rail Dart Mk3', 'Hardened Rail Dart Mk2', 'Rail Gun', null, null, null, null),
('Hardened Sensor Tower', 'Improved Hardcrete Mk2', 'Sensor Tower', null, null, null, null),
('HE Howitzer Shells', 'Howitzer', null, null, null, null, null),
('HE Howitzer Shells Mk2', 'HE Howitzer Shells', null, null, null, null, null),
('HE Howitzer Shells Mk3', 'HE Howitzer Shells Mk2', null, null, null, null, null),
('HE Mini-Rockets', 'Mini-Pod Rockets', null, null, null, null, null),
('HE Mini-Rockets Mk2', 'HE Mini-Rockets', null, null, null, null, null),
('HE Mini-Rockets Mk3', 'HE Mini-Rockets Mk2', null, null, null, null, null),
('HE Mortar Shells', 'Mortar', null, null, null, null, null),
('HE Mortar Shells Mk2', 'HE Mortar Shells', null, null, null, null, null),
('HE Mortar Shells Mk3', 'HE Mortar Shells Mk2', null, null, null, null, null),
('HEAP Bomb Bay', 'Cluster Bombs Bay', 'Thermal Imaging Bombsight', null, null, null, null),
('HEAP Howitzer Shells', 'Rotary Howitzer - Hellstorm', 'HVAPFSDS Cannon Rounds', null, null, null, null),
('HEAP Howitzer Shells Mk2', 'HEAP Howitzer Shells', null, null, null, null, null),
('HEAP Howitzer Shells Mk3', 'HEAP Howitzer Shells Mk2', null, null, null, null, null),
('HEAP Mini-Rockets', 'HE Mini-Rockets Mk3', null, null, null, null, null),
('HEAP Mini-Rockets Mk2', 'HEAP Mini-Rockets', null, null, null, null, null),
('HEAP Mini-Rockets Mk3', 'HEAP Mini-Rockets Mk2', null, null, null, null, null),
('HEAP Mortar Shells', 'Heavy Mortar - Bombard', 'HE Mortar Shells Mk3', null, null, null, null),
('HEAP Mortar Shells Mk2', 'HEAP Mortar Shells', null, null, null, null, null),
('HEAP Mortar Shells Mk3', 'HEAP Mortar Shells Mk2', null, null, null, null, null),
('HEAT Cannon Shells', 'Light Cannon', null, null, null, null, null),
('HEAT Cannon Shells Mk2', 'HEAT Cannon Shells', null, null, null, null, null),
('HEAT Cannon Shells Mk3', 'HEAT Cannon Shells Mk2', null, null, null, null, null),
('HEAT Rocket Warhead', 'Lancer AT Rocket', null, null, null, null, null),
('HEAT Rocket Warhead Mk2', 'HEAT Rocket Warhead', null, null, null, null, null),
('HEAT Rocket Warhead Mk3', 'HEAT Rocket Warhead Mk2', null, null, null, null, null),
('Heavy Body - Mantis', 'Heavy Body - Python', 'Dense Composite Alloys Mk2', null, null, null, null),
('Heavy Body - Python', 'Medium Body - Cobra', 'Composite Alloys Mk2', null, null, null, null),
('Heavy Body - Tiger', 'Composite Alloys Mk3', 'Heavy Body - Python', 'Medium Body - Panther', null, null, null),
('Heavy Body - Vengeance', 'Heavy Body - Tiger', 'Superdense Composite Alloys Mk3', 'Medium Body - Retribution', null, null, null),
('Heavy Cannon', 'HEAT Cannon Shells Mk3', 'Factory Module', 'Heavy Body - Python', 'Medium Cannon', null, null),
('Heavy Cannon Hardpoint', 'Medium Cannon Hardpoint', 'Heavy Cannon', null, null, null, null),
('Heavy Flamer - Inferno', 'Medium Body - Cobra', 'Superhot Flamer Gel', 'Flamer', null, null, null),
('Heavy Gunner', 'Machine Gunner', 'Light Cannon', null, null, null, null),
('Heavy Howitzer - Ground Shaker', 'HE Howitzer Shells Mk2', 'Howitzer', null, null, null, null),
('Heavy Laser', 'Pulse Laser', null, 'Flashlight', null, null, null),
('Heavy Laser Emplacement', 'Heavy Laser', null, null, null, null, null),
('Heavy Machinegun', 'APDSB MG Bullets', 'Twin Machinegun', null, null, null, null),
('Heavy Machinegun Hardpoint', 'Machinegun Bunker', 'Hardcrete', 'Heavy Machinegun', null, null, null),
('Heavy Mortar - Bombard', 'Composite Alloys', 'HE Mortar Shells Mk2', 'Mortar', null, null, null),
('Heavy Repair Turret', 'Advanced Engineering', null, null, null, null, null),
('Heavy Rocket Bastion', 'Thermal Imaging Rockets', 'Supercrete Mk2', 'HESH Rocket Warhead Mk3', null, null, null),
('Hellstorm Emplacement', 'Rotary Howitzer - Hellstorm', null, null, null, null, null),
('HESH Rocket Warhead', 'HEAT Rocket Warhead Mk3', null, null, null, null, null),
('HESH Rocket Warhead Mk2', 'HESH Rocket Warhead', null, null, null, null, null),
('HESH Rocket Warhead Mk3', 'HESH Rocket Warhead Mk2', null, null, null, null, null),
('Hi-Energy Laser Emitter', 'Improved Laser Focusing', null, null, null, null, null),
('Hi-Energy Laser Emitter Mk2', 'Hi-Energy Laser Emitter', null, null, null, null, null),
('Hi-Energy Laser Emitter Mk3', 'Hi-Energy Laser Emitter Mk2', null, null, null, null, null),
('High Intensity Thermal Armor', 'Thermal Amour Mk3', 'Superdense Composite Alloys', null, null, null, null),
('High Intensity Thermal Armor Mk2', 'High Intensity Thermal Armor', null, null, null, null, null),
('High Intensity Thermal Armor Mk3', 'High Intensity Thermal Armor Mk2', null, null, null, null, null),
('High Temperature Flamer Gel', 'Flamer', null, null, null, null, null),
('High Temperature Flamer Gel Mk2', 'High Temperature Flamer Gel', null, null, null, null, null),
('High Temperature Flamer Gel Mk3', 'High Temperature Flamer Gel Mk2', null, null, null, null, null),
('Hover Propulsion', 'Fuel Injection Engine Mk2', 'Factory Module', null, null, null, null),
('Howitzer', 'HEAP Mortar Shells', 'Sensor Upgrade', null, null, null, null),
('Howitzer Autoloader', 'Heavy Howitzer - Ground Shaker', null, null, null, null, null),
('Howitzer Autoloader Mk2', 'Howitzer Autoloader', null, null, null, null, null),
('Howitzer Autoloader Mk3', 'Howitzer Autoloader Mk2', null, null, null, null, null),
('Howitzer Emplacement', 'Howitzer', null, null, null, null, null),
('HPV Cannon Emplacement', 'Hyper Velocity Cannon', null, null, null, null, null),
('HPV Cannon Hardpoint', 'Hyper Velocity Cannon', null, null, null, null, null),
('Hurricane AA Site', 'Hurricane AA Turret', null, null, null, null, null),
('Hurricane AA Turret', 'Twin Machinegun', null, null, null, null, null),
('HVAPFSDS Cannon Rounds', 'APFSDS Cannon Rounds Mk3', null, null, null, null, null),
('HVAPFSDS Cannon Rounds Mk2', 'HVAPFSDS Cannon Rounds', null, null, null, null, null),
('HVAPFSDS Cannon Rounds Mk3', 'HVAPFSDS Cannon Rounds Mk2', null, null, null, null, null),
('Hyper Fire Chaingun Upgrade', 'Rapid Fire Chaingun', null, null, null, null, null),
('Hyper Velocity Cannon', 'APFSDS Cannon Rounds Mk2', 'Medium Cannon', null, null, null, null),
('Improved Engineering', 'Engineering', 'Dedicated Synaptic Link Data Analysis', null, null, null, null),
('Improved Hardcrete', 'Engineering', 'Hardcrete', null, null, null, null),
('Improved Hardcrete Mk2', 'Improved Hardcrete', null, null, null, null, null),
('Improved Hardcrete Mk3', 'Improved Hardcrete Mk2', null, null, null, null, null),
('Improved Laser Focusing', 'Laser - Flashlight', null, null, null, null, null),
('Improved Rocket Wire Guidance', 'HEAT Rocket Warhead', 'Synaptic Link Data Analysis Mk2', null, null, null, null),
('Incendiary Howitzer', 'Heavy Flamer - Inferno', 'HE Howitzer Shells Mk3', 'Heavy Howitzer - Ground Shaker', null, null, null),
('Incendiary Howitzer Emplacement', 'Howitzer Emplacement', 'Incendiary Howitzer', null, null, null, null),
('Incendiary Mortar', 'Neural Synapse Research Brain', 'Heavy Mortar - Bombard', 'Heavy Flamer - Inferno', null, null, null),
('Inferno Emplacement', 'Heavy Flamer - Inferno', null, null, null, null, null),
('Lancer', 'Machine Gunner', 'Lancer AT Rocket', null, null, null, null),
('Lancer AT Rocket', 'HE Mini-Rockets Mk2', null, null, null, null, null),
('Lancer Bunker', 'Hardcrete', 'Lancer AT Rocket', null, null, null, null),
('Lancer Hardpoint', 'Lancer AT Rocket', 'Hardcrete', null, null, null, null),
('Laser - Flashlight', 'Neural Synapse Research Brain Mk3', 'Sensor Upgrade', null, null, null, null),
('Laser Guided Bombsight', 'Thermal Imaging Bombsight', null, null, null, null, null),
('Laser Satellite Command Post', 'Neural Synapse Research Brain Mk3', 'Satellite Uplink Center', null, null, null, null),
('Light Body - Bug', 'Composite Alloys', null, null, null, null, null),
('Light Body - Leopard', null, 'Dense Composite Alloys', null, null, null, null),
('Light Body - Retaliation', 'Superdense Composite Alloys', 'Light Body - Bug', null, null, null, null),
('Light Cannon', 'Hardened MG Bullets', null, null, null, null, null),
('Light Cannon Bunker', 'Hardcrete', 'Light Cannon', null, null, null, null),
('Light Cannon Hardpoint', 'Hardcrete', 'Light Cannon', null, null, null, null),
('Machine Gunner', 'Cyborg Factory', null, null, null, null, null),
('Machinegun', null, null, null, null, null, null),
('Machinegun Bunker', 'Hardcrete', 'Hardened MG Bullets', null, null, null, null),
('Machinegun Guard Tower', 'Machinegun', null, null, null, null, null),
('Mass Driver Fortress', 'Gauss Cannon', 'Rail Gun ROF Mk3', 'Plasteel', null, null, null),
('Medium Body - Cobra', 'Factory Module', null, null, null, null, null),
('Medium Body - Panther', 'Light Body - Leopard', 'Factory Module', 'Medium Body - Cobra', null, null, null),
('Medium Body - Retribution', 'Factory Module', 'Medium Body - Panther', 'Superdense Composite Alloys Mk2', 'Light Body - Retaliation', null, null),
('Medium Body - Scorpion', 'Medium Body - Cobra', 'Composite Alloys Mk2', null, null, null, null),
('Medium Cannon', 'Factory Module', 'HEAT Cannon Shells', null, null, null, null),
('Medium Cannon Hardpoint', 'Medium Cannon', 'Light Cannon Hardpoint', null, null, null, null),
('Mini-Pod Rocket Guard Tower', 'Hardcrete', 'Mini-Pod Rockets', null, null, null, null),
('Mini-Pod Rockets', 'Fuel Injection Engine', null, null, null, null, null),
('Mini-Rocket Artillery', 'HE Mini-Rockets', null, null, null, null, null),
('Mini-Rocket Battery', 'Mini-Rocket Artillery', 'Hardcrete', null, null, null, null),
('Missile Fortress', 'Plasteel', 'Scourge Missile', 'Advanced Missile Allocation System Mk3', null, null, null),
('Mobile Repair Turret', 'Engineering', null, null, null, null, null),
('Mortar', 'HEAT Cannon Shells', 'Factory Module', null, null, null, null),
('Mortar Autoloader', 'HE Mortar Shells Mk3', null, null, null, null, null),
('Mortar Autoloader Mk2', 'Mortar Autoloader', 'Heavy Mortar - Bombard', null, null, null, null),
('Mortar Autoloader Mk3', 'Mortar Autoloader Mk2', null, null, null, null, null),
('Mortar Fast Loader', 'Cannon Rapid Loader', null, null, null, null, null),
('Mortar Pit', 'Hardcrete', 'Mortar', null, null, null, null),
('Mortar Targeting Computer', 'Synaptic Link Data Analysis Mk2', 'HE Mortar Shells', null, null, null, null),
('Needle Gun', 'Hyper Velocity Cannon', 'Neural Synapse Research Brain Mk2', 'HVAPFSDS Cannon Rounds', null, null, null),
('Needle Gun Tower', 'Needle Gun', null, null, null, null, null),
('Needle Gunner', 'Needle Gun', null, null, null, null, null),
('Neural Synapse Research Brain', 'Dedicated Synaptic Link Data Analysis Mk3', null, null, null, null, null),
('Neural Synapse Research Brain Mk2', 'Neural Synapse Research Brain', null, null, null, null, null),
('Neural Synapse Research Brain Mk3', 'Neural Synapse Research Brain Mk2', null, null, null, null, null),
('Nexus Link Tower', 'Nexus Link Turret', null, null, null, null, null),
('Nexus Link Turret', 'Advanced Engineering', 'Neural Synapse Research Brain Mk2', 'Wide Spectrum Sensor Tower', null, null, null),
('Pepperpot Pit', 'Rotary Mortar - Pepperpot', null, null, null, null, null),
('Phosphor Bomb Bay', 'Cluster Bombs Bay', 'Superhot Flamer Gel', null, null, null, null),
('Plascrete', 'Supercrete Mk3', 'Advanced Engineering', null, null, null, null),
('Plascrete Mk2', 'Plascrete', null, null, null, null, null),
('Plascrete MK3', 'Plascrete Mk2', null, null, null, null, null),
('Plasma Cannon', 'Heavy Laser', null, null, null, null, null),
('Plasma Cannon Emplacement', 'Plasma Cannon', null, null, null, null, null),
('Plasmite Bomb', 'Plasmite Flamer', 'Thermite Bomb Bay', null, null, null, null),
('Plasmite Flamer', 'Heavy Flamer - Inferno', 'Neural Synapse Research Brain', 'Inferno', null, null, null),
('Plasteel', 'Plascrete MK3', null, null, null, null, null),
('Plasteel Mk2', 'Plasteel', null, null, null, null, null),
('Plasteel Mk3', 'Plasteel Mk2', null, null, null, null, null),
('Power Module', 'Fuel Injection Engine', null, null, null, null, null),
('Pulse Laser', 'Laser - Flashlight', null, null, null, null, null),
('Pulse Laser Emplacement', 'Pulse Laser', null, null, null, null, null),
('Rail Gun', 'Hardened Rail Dart Mk2', 'Needle Gun', null, 'Needle Gun', null, null),
('Rail Gun Emplacement', 'Rail Gun', null, null, null, null, null),
('Rail Gun Hardpoint', 'Rail Gun', null, null, null, null, null),
('Rail Gun ROF', 'Target Prediction Computer', null, null, null, null, null),
('Rail Gun ROF Mk2', 'Rail Gun ROF', null, null, null, null, null),
('Rail Gun ROF Mk3', 'Rail Gun ROF Mk2', null, null, null, null, null),
('Rapid Fire Chaingun', 'Chaingun Upgrade', null, null, null, null, null),
('Reinforced Base Structure Materials', 'Improved Hardcrete', null, null, null, null, null),
('Reinforced Base Structure Materials Mk2', 'Reinforced Base Structure Materials', null, null, null, null, null),
('Reinforced Base Structure Materials Mk3', 'Reinforced Base Structure Materials Mk2', null, null, null, null, null),
('Repair Facility', 'Mobile Repair Turret', 'Factory Module', null, null, null, null),
('Research Module', 'Command Relay Post', null, null, null, null, null),
('Resistance Circuits', 'Advanced Engineering', 'Neural Synapse Research Brain Mk2', 'Wide Spectrum Sensor Tower', null, null, null),
('Ripple Rocket Battery', 'Ripple Rockets', 'Mini-Rocket Battery', null, null, null, null),
('Ripple Rockets', 'Mini-Rocket Artillery', 'CB Tower', null, null, null, null),
('Robotic Cyborg Production', 'Automated Cyborg Production Mk3', null, null, null, null, null),
('Robotic Cyborg Production Mk2', 'Robotic Cyborg Production', null, null, null, null, null),
('Robotic Cyborg Production Mk3', 'Robotic Cyborg Production Mk2', null, null, null, null, null),
('Robotic Factory Production', 'Automated Factory Production Mk3', null, null, null, null, null),
('Robotic Factory Production Mk2', 'Robotic Factory Production', null, null, null, null, null),
('Robotic Factory Production Mk3', 'Robotic Factory Production Mk2', null, null, null, null, null),
('Robotic Repair Facility Upgrade', 'Automated Repair Facility Upgrade Mk3', null, null, null, null, null),
('Robotic Repair Facility Upgrade Mk2', 'Robotic Repair Facility Upgrade', null, null, null, null, null),
('Robotic Repair Facility Upgrade Mk3', 'Robotic Repair Facility Upgrade Mk2', null, null, null, null, null),
('Robotic VTOL Production', 'VTOL Rearming Pad', null, null, null, null, null),
('Robotic VTOL Production Mk2', 'Robotic VTOL Production', null, null, null, null, null),
('Robotic VTOL Production Mk3', 'Robotic VTOL Production Mk2', null, null, null, null, null),
('Robotic VTOL Rearming', 'Robotic VTOL Production Mk3', null, null, null, null, null),
('Robotic VTOL Rearming Mk2', 'Robotic VTOL Rearming', null, null, null, null, null),
('Robotic VTOL Rearming Mk3', 'Robotic VTOL Rearming Mk2', null, null, null, null, null),
('Rocket Autoloader', 'HEAP Mini-Rockets', null, null, null, null, null),
('Rocket Autoloader Mk2', 'Rocket Autoloader', null, null, null, null, null),
('Rocket Laser Designator', 'Improved Rocket Wire Guidance', null, null, null, null, null),
('Rotary Howitzer - Hellstorm', 'HE Howitzer Shells Mk3', 'Heavy Howitzer - Ground Shaker', 'Howitzer', null, null, null),
('Rotary Mortar - Pepperpot', 'Heavy Mortar - Bombard', 'Mortar Autoloader Mk3', 'Mortar', null, null, null),
('Satellite Uplink Center', 'Neural Synapse Research Brain Mk2', 'Wide Spectrum Sensor Tower', 'Advanced Engineering', null, null, null),
('Scourge', 'Scourge Missile', null, null, null, null, null),
('Scourge Missile', 'Tank Killer Rocket', 'Neural Synapse Research Brain', 'Lancer', null, null, null),
('Scourge Missile Hardpoint', 'Scourge Missile', null, null, null, null, null),
('Scourge Missile Tower', 'Scourge Missile', null, null, null, null, null),
('Search & Destroy Missiles', 'Target Prediction Missiles', null, null, null, null, null),
('Sensor Tower', 'Machinegun Guard Tower', 'Sensor Turret', null, null, null, null),
('Sensor Turret', null, null, null, null, null, null),
('Sensor Upgrade', 'Dedicated Synaptic Link Data Analysis', 'Sensor Tower', null, null, null, null),
('Stabilized Mini-Rockets', 'Synaptic Link Data Analysis', 'HE Mini-Rockets Mk2', null, null, null, null),
('Stabilized Mini-Rockets Mk2', 'Stabilized Mini-Rockets', 'Synaptic Link Data Analysis Mk2', null, null, null, null),
('Stormbringer AA Laser', 'Thermopole Energizer Mk3', 'Whirlwind AA Turret', null, null, null, null),
('Super Auto-Cannon Cyborg', 'Assault Cannon', 'Super HPV Cyborg', null, null, null, null),
('Super Heavy Body - Dragon', 'Superdense Composite Alloys Mk3', 'Gas Turbine Engine Mk3', 'High Intensity Thermal Armor Mk3', 'Super Heavy Body - Wyvern', null, null),
('Super Heavy Body - Wyvern', 'Superdense Composite Alloys Mk3', 'Gas Turbine Engine Mk3', 'High Intensity Thermal Armor Mk3', 'Heavy Body - Vengeance', null, null),
('Super Heavy-Gunner', 'Heavy Gunner', 'Cyborg Dense Composite Alloys', 'Medium Cannon', null, null, null),
('Super HPV Cyborg', 'Super Heavy-Gunner', 'Hyper Velocity Cannon', null, null, null, null),
('Super Pulse Laser Cyborg', 'Pulse Laser', null, null, null, null, null),
('Super Rail-Gunner', 'Rail Gun', null, null, null, null, null),
('Super Scourge Cyborg', 'Scourge', 'Scourge Missile', null, null, null, null),
('Super Tank-Killer Cyborg', 'Cyborg Dense Composite Alloys', 'Tank Killer Rocket', null, null, null, null),
('Supercrete', 'Improved Engineering', 'Dedicated Synaptic Link Data Analysis', 'Improved Hardcrete Mk3', null, null, null),
('Supercrete Mk2', 'Supercrete', null, null, null, null, null),
('Supercrete Mk3', 'Supercrete Mk2', null, null, null, null, null),
('Superdense Composite Alloys', 'Neural Synapse Research Brain', 'Dense Composite Alloys Mk3', null, null, null, null),
('Superdense Composite Alloys Mk2', 'Superdense Composite Alloys', null, null, null, null, null),
('Superdense Composite Alloys Mk3', 'Superdense Composite Alloys Mk2', null, null, null, null, null),
('Superhot Flamer Gel', 'High Temperature Flamer Gel Mk3', null, null, null, null, null),
('Superhot Flamer Gel Mk2', 'Superhot Flamer Gel', null, null, null, null, null),
('Superhot Flamer Gel Mk3', 'Superhot Flamer Gel Mk2', null, null, null, null, null),
('Superhot Plasmite gel', 'Superhot Flamer Gel Mk3', 'Plasmite Flamer', null, null, null, null),
('Superhot Plasmite gel Mk2', 'Superhot Plasmite gel', null, null, null, null, null),
('Superhot Plasmite gel Mk3', 'Superhot Plasmite gel Mk2', null, null, null, null, null),
('Synaptic Link Data Analysis', 'Research Module', null, null, null, null, null),
('Synaptic Link Data Analysis Mk2', 'Synaptic Link Data Analysis', null, null, null, null, null),
('Synaptic Link Data Analysis Mk3', 'Synaptic Link Data Analysis Mk2', null, null, null, null, null),
('Tank Killer Emplacement', 'Tank Killer Rocket', null, null, null, null, null),
('Tank Killer Hardpoint', 'Tank Killer Rocket', null, null, null, null, null),
('Tank Killer Rocket', 'Rocket Laser Designator', 'HESH Rocket Warhead', null, null, null, null),
('Tank Traps', 'Engineering', null, null, null, null, null),
('Target Acquisition Artillery Shells', 'Howitzer', null, null, null, null, null),
('Target Acquisition Artillery Shells Mk2', 'Dedicated Synaptic Link Data Analysis', 'Target Acquisition Artillery Shells', null, null, null, null),
('Target Acquisition Bombsight', 'Thermal Imaging Mortar Shells', null, null, null, null, null),
('Target Acquisition Mortar Shells', 'Neural Synapse Research Brain Mk2', 'Thermal Imaging Mortar Shells', null, null, null, null),
('Target Prediction Artillery Shells', 'Target Acquisition Artillery Shells Mk2', null, null, null, null, null),
('Target Prediction Computer', 'Hardened Rail Dart', null, null, null, null, null),
('Target Prediction Missiles', 'Advanced Missile Warhead', null, null, null, null, null),
('Thermal Amour', 'Dense Composite Alloys', null, null, null, null, null),
('Thermal Amour Mk2', 'Thermal Amour', null, null, null, null, null),
('Thermal Amour Mk3', 'Thermal Amour Mk2', null, null, null, null, null),
('Thermal Imaging Bombsight', 'Thermal Imaging Mortar Shells', 'Cluster Bombs Bay', 'VTOL Propulsion', null, null, null),
('Thermal Imaging Mortar Shells', 'Mortar Targeting Computer', 'Dedicated Synaptic Link Data Analysis', null, null, null, null),
('Thermal Imaging Rockets', 'Dedicated Synaptic Link Data Analysis', 'Rocket Laser Designator', null, null, null, null),
('Thermite Bomb Bay', 'Superhot Flamer Gel Mk2', 'Phosphor Bomb Bay', null, null, null, null),
('Thermite Flamer', 'Heavy Flamer - Inferno', 'Flamer', null, null, null, null),
('Thermopole Energizer', 'Hi-Energy Laser Emitter', null, null, null, null, null),
('Thermopole Energizer Mk2', 'Thermopole Energizer', null, null, null, null, null),
('Thermopole Energizer Mk3', 'Thermopole Energizer Mk2', null, null, null, null, null),
('Tracked Propulsion', 'Engineering', 'Half-tracked Propulsion', null, null, null, null),
('Turbo-Charged Engine', 'VTOL Propulsion', 'Gas Turbine Generator', null, null, null, null),
('Turbo-Charged Engine Mk2', 'Turbo-Charged Engine', null, null, null, null, null),
('Turbo-Charged Engine Mk3', 'Turbo-Charged Engine Mk2', null, null, null, null, null),
('Twin Assault Cannon', 'Assault Cannon', 'Neural Synapse Research Brain', null, null, null, null),
('Twin Assault Cannon Bunker', 'Supercrete', 'Twin Assault Cannon', null, null, null, null),
('Twin Assault Gun', 'Neural Synapse Research Brain', 'Assault Gun', 'Assault Gun', null, null, null),
('Twin Machinegun', 'APDSB MG Bullets', null, null, null, null, null),
('Vapor Turbine Generator', 'Neural Synapse Research Brain', 'Gas Turbine Generator', null, null, null, null),
('Vehicle Superdense Thermal Armor', 'High Intensity Thermal Armor Mk3', null, null, null, null, null),
('Vehicle Superdense Thermal Armor Mk2', 'Vehicle Superdense Thermal Armor', null, null, null, null, null),
('Vehicle Superdense Thermal Armor Mk3', 'Vehicle Superdense Thermal Armor Mk2', null, null, null, null, null),
('Vindicator Hardpoint', 'Vindicator SAM', 'Plascrete', null, null, null, null),
('Vindicator SAM', 'Advanced Missile Warhead Mk3', 'Avenger SAM', null, null, null, null),
('Vindicator SAM Site', 'Vindicator SAM', null, null, null, null, null),
('VTOL CB Tower', 'VTOL Strike Tower', 'CB Tower', null, null, null, null),
('VTOL CB Turret', 'VTOL CB Tower', 'CB Turret', null, null, null, null),
('VTOL Factory', 'VTOL Propulsion', null, null, null, null, null),
('VTOL Propulsion', 'Automated Factory Production', 'Hover Propulsion', 'Fuel Injection Engine Mk3', null, null, null),
('VTOL Rearming Pad', 'VTOL Propulsion', 'VTOL Factory', null, null, null, null),
('VTOL Strike Tower', 'VTOL Rearming Pad', 'Sensor Upgrade', null, null, null, null),
('VTOL Strike Turret', 'VTOL Strike Tower', 'Sensor Turret', null, null, null, null),
('Whirlwind AA Site', 'Whirlwind AA Turret', 'Hurricane AA Site', null, null, null, null),
('Whirlwind AA Turret', 'Assault Gun', 'Cyclone Flak Turret', 'Cyclone Flak Turret', 'Hurricane AA Turret', null, null),
('Whirlwind Hardpoint', 'Hardcrete', 'Whirlwind AA Site', null, null, null, null),
('Wide Spectrum Sensor', 'Neural Synapse Research Brain', 'VTOL CB Tower', 'Hardened Sensor Tower', 'VTOL Strike Tower', 'CB Tower', null),
('Wide Spectrum Sensor Tower', 'VTOL Strike Tower', 'CB Tower', 'VTOL CB Tower', 'Hardened Sensor Tower', 'Neural Synapse Research Brain', 'Wide Spectrum Sensor');

insert into dependency
select tech.id, req.id
from temp
join tech on temp.tech = tech.name
join tech req on temp.name1 = req.name
where temp.name1 is not null;

insert into dependency
select tech.id, req.id
from temp
join tech on temp.tech = tech.name
join tech req on temp.name2 = req.name
where temp.name2 is not null;

insert into dependency
select tech.id, req.id
from temp
join tech on temp.tech = tech.name
join tech req on temp.name3 = req.name
where temp.name3 is not null;

insert into dependency
select tech.id, req.id
from temp
join tech on temp.tech = tech.name
join tech req on temp.name4 = req.name
where temp.name4 is not null;

insert into dependency
select tech.id, req.id
from temp
join tech on temp.tech = tech.name
join tech req on temp.name5 = req.name
where temp.name5 is not null;

insert into dependency
select tech.id, req.id
from temp
join tech on temp.tech = tech.name
join tech req on temp.name6 = req.name
where temp.name6 is not null;

drop table temp;